from figures import (
    TR_INDIVS_BOXPLOT_LINE_MEAN_STAT_MEAN,
    TR_INDIVS_BOXPLOT_LINE_MEAN_STAT_MEAN_BL,
    TR_INDIVS_BOXPLOT_LINE_MEDIAN_STAT_MEDIAN,
    TR_INDIVS_BOXPLOT_LINE_MEDIAN_STAT_MEDIAN_BL,
    TR_INDIVS_BOXPLOT_LINE_REPLICATE_MEAN_STAT_MEAN,
    TR_INDIVS_BOXPLOT_LINE_REPLICATE_MEAN_STAT_MEAN_BL,
    TR_INDIVS_BOXPLOT_LINE_REPLICATE_MEDIAN_STAT_MEDIAN,
    TR_INDIVS_BOXPLOT_LINE_REPLICATE_MEDIAN_STAT_MEDIAN_BL,
)
from plotters import plot

plot_configs = [
    TR_INDIVS_BOXPLOT_LINE_MEAN_STAT_MEAN,
    TR_INDIVS_BOXPLOT_LINE_MEAN_STAT_MEAN_BL,
    TR_INDIVS_BOXPLOT_LINE_MEDIAN_STAT_MEDIAN,
    TR_INDIVS_BOXPLOT_LINE_MEDIAN_STAT_MEDIAN_BL,
    TR_INDIVS_BOXPLOT_LINE_REPLICATE_MEAN_STAT_MEAN,
    TR_INDIVS_BOXPLOT_LINE_REPLICATE_MEAN_STAT_MEAN_BL,
    TR_INDIVS_BOXPLOT_LINE_REPLICATE_MEDIAN_STAT_MEDIAN,
    TR_INDIVS_BOXPLOT_LINE_REPLICATE_MEDIAN_STAT_MEDIAN_BL,
]

for plot_config in plot_configs:

    data_filtered_stat, all_var_stats, all_outliers = plot(plot_config.copy())
