name: mic_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - ipywidgets
  - jupyter
  - pip=20.3.4
  - pip:
    - idtrackerai
    - tqdm
    - mlxtend
    - confapp
    - miniball
    - blackcellmagic
    - natsort
    - black
variables:
  DATA_DIR: "/home/pacorofe/Dropbox (CRG ADV)/ZFISH_MICs/_BSocial/2022_ANALYSIS_social"
